language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

jobs:
  include:
    - os: osx
      language: generic
      env: MACOSX_DEPLOYMENT_TARGET=10.12

install:
  - pip install flake8 pytest-cov coveralls

script:
  - flake8
  - pytest --cov

after_success:
  - coveralls
