version: 1.0.{build}

environment:
  matrix:
  - Python: 27-x64
  - Python: 35-x64
  - Python: 36-x64
  - Python: 37-x64
  - Python: 38-x64

build_script:
  - PATH %CD%\here\bin;C:\mingw\bin;C:\python%Python%;C:\python%Python%\scripts;%PATH%
  - pip install flake8 pytest-cov coveralls

test_script:
  - flake8
  - pytest --cov

on_success:
  - if not "%COVERALLS_REPO_TOKEN%"=="" coveralls
